sonar.projectKey=fastapi-cicd
sonar.projectName=FastAPI CI/CD Pipeline
sonar.sources=src
sonar.tests=test
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/migrations/**
